version: '3.8'

services:
    web:
      build: 
        context: ./bookstore
        dockerfile: Dockerfile.prod
      command: gunicorn bookstore.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - static_volume:/home/app/web/staticfiles
      expose:
        - 8000
      env_file:
        - ./.env.prod
      depends_on:
        - mongo
    mongo:
      image: mongo
      volumes:
        - mongo_data:/var/lib/mongodb/data/
      env_file:
        - ./.env.prod.db
    nginx:
      build: ./nginx
      volumes:
        - static_volume:/home/app/web/staticfiles
      ports:
        - 80:80
      depends_on:
        - web
volumes:
  mongo_data:
  static_volume:
