# Generated by Django 3.0.5 on 2020-11-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(default='', max_length=13)),
                ('title', models.CharField(default='', max_length=100)),
                ('author_last_name', models.CharField(default='', max_length=50)),
                ('author_first_name', models.CharField(default='', max_length=50)),
                ('page_count', models.PositiveSmallIntegerField()),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
